
CREATE DATABASE IF NOT EXISTS kampus;
USE kampus;

CREATE TABLE IF NOT EXISTS mahasiswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100),
    nim VARCHAR(20)
);

INSERT INTO mahasiswa (nama, nim) VALUES
('AJRUN KABIR', 'A12.2023.07023'),
('BUDI SANTOSO', '23001'),
('DEWI ANGGRAINI', '23002');
